# Generated by Django 3.1.7 on 2021-04-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=55)),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Likert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=70)),
                ('timestamp', models.CharField(max_length=60)),
                ('a1', models.CharField(max_length=255)),
                ('a2', models.CharField(max_length=255)),
                ('a3', models.CharField(max_length=255)),
                ('a4', models.CharField(max_length=255)),
                ('a5', models.CharField(max_length=255)),
                ('a6', models.CharField(max_length=255)),
                ('a7', models.CharField(max_length=255)),
                ('a8', models.CharField(max_length=255)),
                ('a9', models.CharField(max_length=255)),
                ('a10', models.CharField(max_length=255)),
                ('a11', models.CharField(max_length=255)),
                ('a12', models.CharField(max_length=255)),
                ('a13', models.CharField(max_length=255)),
                ('a14', models.CharField(max_length=255)),
                ('a15', models.CharField(max_length=255)),
                ('a16', models.CharField(max_length=255)),
                ('a17', models.CharField(max_length=255)),
                ('i1', models.CharField(max_length=255)),
                ('i2', models.CharField(max_length=255)),
                ('i3', models.CharField(max_length=255)),
                ('ac1', models.CharField(max_length=255)),
                ('ac2', models.CharField(max_length=255)),
                ('ac3', models.CharField(max_length=255)),
                ('ac4', models.CharField(max_length=255)),
                ('ac5', models.CharField(max_length=255)),
                ('ac6', models.CharField(max_length=255)),
                ('ac7', models.CharField(max_length=255)),
                ('ac8', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'likert',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e1', models.CharField(max_length=255)),
                ('e2', models.CharField(max_length=255)),
                ('e3', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'opinion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=55)),
                ('timestamp', models.CharField(max_length=70)),
                ('a1', models.CharField(max_length=255)),
                ('a2', models.CharField(max_length=255)),
                ('a3', models.CharField(max_length=255)),
                ('a4', models.CharField(max_length=255)),
                ('a5', models.CharField(max_length=255)),
                ('a6', models.CharField(max_length=255)),
                ('a7', models.CharField(max_length=255)),
                ('a8', models.CharField(max_length=255)),
                ('a9', models.CharField(max_length=255)),
                ('a10', models.CharField(max_length=255)),
                ('a11', models.CharField(max_length=255)),
                ('a12', models.CharField(max_length=255)),
                ('a13', models.CharField(max_length=255)),
                ('a14', models.CharField(max_length=255)),
                ('i1', models.CharField(max_length=255)),
                ('i2', models.CharField(max_length=255)),
                ('i3', models.CharField(max_length=255)),
                ('ac1', models.CharField(max_length=255)),
                ('ac2', models.CharField(max_length=255)),
                ('ac3', models.CharField(max_length=255)),
                ('ac4', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'survey',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Surveyquestions',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_description', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'surveyquestions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=55)),
                ('role', models.CharField(max_length=55)),
                ('is_user', models.IntegerField()),
                ('is_admin', models.IntegerField()),
                ('is_itbl', models.IntegerField()),
                ('is_ito', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
